### PR TITLE
Add function for getting just the yaml key into the winbar

### PR DESCRIPTION
**Pull request by joshzcold**
get_yaml_key_and_value can be distracting with large yaml values, so this is another option for those that might want it

### CODE REVIEW

**Comment by joshzcold** [comment]
image

Helps out when the value would be unreable in the winbar.

just using get_yaml_key is much easier to process.

**Comment by cuducos** [comment]
Hi : ) I think you need to rebase your branch. I see some outdated bits on the `README.me` (section headings, for example), and in the Lua file (e.g. `assure_yaml_filetype` is now gone in the main branch)… would you mind double-checking this, please? Otherwise, if you allow, I can merge that to a feature branch and work on it myself instead.

**Comment by joshzcold** [comment]
Done, thank you 👍

**Comment by cuducos** [comment]
Thank you so much 💜

**Pull request merged**
